# SELECT COUNT(USER_ID) 
# FROM USER_INFO
# WHERE DATET_FORMAT(JOINED, '%Y') LIKE '2021%' AND AGE >= 20 AND AGE < 30;

SELECT COUNT(USER_ID)
FROM USER_INFO
WHERE DATE_FORMAT(JOINED, '%Y') LIKE '2021%' AND AGE >= 20 AND AGE < 30;
