-- 코드를 입력하세요
WITH RECURSIVE HOUR_TABLE AS (
    SELECT 0 AS hour
    UNION ALL
    SELECT hour + 1 FROM HOUR_TABLE WHERE hour < 23
)


SELECT hour, COUNT(ANIMAL_ID)
FROM HOUR_TABLE
LEFT JOIN ANIMAL_OUTS
ON HOUR_TABLE.hour = DATE_FORMAT(DATETIME, "%H")
GROUP BY hour;
