-- 코드를 입력하세요
/*
MEMBER_PROFILE 테이블에서 여성 회원 ID, 이름, 성별, 생년월일 조회
만약 전화번호가 NULL이면 제외
회원ID 기준으로 오름차순 정렬
*/

SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE DATE_OF_BIRTH LIKE '%-03%' AND GENDER = 'W' AND TLNO IS NOT NULL
ORDER BY MEMBER_ID

# SELECT *
# FROM MEMBER_PROFILE