-- 코드를 입력하세요
SELECT FLAVOR
FROM FIRST_HALF
WHERE TOTAL_ORDER > 3000
HAVING FLAVOR IN (
    SELECT FLAVOR
    FROM ICECREAM_INFO
    WHERE INGREDIENT_TYPE LIKE 'fruit%'
)
ORDER BY TOTAL_ORDER DESC;

# SELECT * FROM ICECREAM_INFO;

# SELECT * FROM FIRST_HALF;